"""Tests for description recognition in _is_generated_by_pr_agent.

The ratchet case from #2633: a description with leading content before
pr-agent headers should still be recognized as pr-agent output, so that
get_user_description can extract the original user text without growing
the description without bound.
"""
import types

from pr_agent.git_providers.git_provider import GitProvider


def _make_provider(desc: str):
    """Create a bare object that has the methods we need to test,
    without instantiating the abstract class."""
    obj = types.SimpleNamespace()
    obj._description = desc
    obj.user_description = None
    obj._UNIQUE_PR_AGENT_HEADERS = GitProvider._UNIQUE_PR_AGENT_HEADERS
    # Bind the real methods from the class
    obj._is_generated_by_pr_agent = lambda d: GitProvider._is_generated_by_pr_agent(obj, d)
    obj._possible_headers = lambda: GitProvider._possible_headers(obj)
    obj.get_pr_description_full = lambda: desc
    return obj


# ---------------------------------------------------------------------------
# Hidden marker detection
# ---------------------------------------------------------------------------

class TestHiddenMarkerDetection:
    def test_marker_anywhere_detects(self):
        desc = ("<!-- pr-agent-generated -->\n"
                "Some text before headers.\n"
                "### **PR Type**\nbug fix")
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_marker_in_body_not_at_start(self):
        desc = ("A sentence.\n\n<!-- pr-agent-generated -->\n\n### **PR Type**\nfeat")
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_no_marker_no_header_returns_false(self):
        desc = "This is a plain human description."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False


# ---------------------------------------------------------------------------
# Leading content tolerance for unique headers
# ---------------------------------------------------------------------------

class TestLeadingContentTolerance:
    """The ratchet case: descriptions with leading content before pr-agent
    headers must still be recognized."""

    def test_leading_sentence_before_pr_type(self):
        desc = "Fixes #42\n### **PR Type**\nbug fix\n### **PR Description**\nFixed the parser."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_leading_sentence_before_pr_description(self):
        desc = "This addresses the regression.\n### **PR Description**\nDone."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_leading_sentence_before_pr_labels(self):
        desc = "Please review.\n### **PR Labels**\nbug, urgent"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_leading_sentence_before_user_description(self):
        desc = "A note from the author.\n### **User Description**\nPlease fix the leak."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_leading_sentence_before_generated_marker(self):
        desc = "FYI\n### \U0001f916 Generated by PR Agent\nSome output."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_multi_line_leading_content(self):
        desc = ("This PR addresses multiple issues:\n"
                "- #100\n"
                "- #200\n\n"
                "### **PR Type**\nfix\n### **PR Description**\nDone.")
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_blank_line_then_sentence_then_header(self):
        desc = "\nHere is a summary.\n### **PR Type**\nfeat"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True


# ---------------------------------------------------------------------------
# Generic headers still require startswith
# ---------------------------------------------------------------------------

class TestGenericHeadersRequireStartswith:
    def test_generic_header_at_start_detected(self):
        desc = "### **Description**\nThis is the description."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_generic_header_with_leading_content_not_detected(self):
        """A human description quoting a generic header should not be
        misclassified as pr-agent output."""
        desc = "Here is my summary.\n### **Description**\nSome content."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_generic_labels_at_start(self):
        desc = "### **Labels**\nbug, enhancement"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_generic_labels_with_leading_not_detected(self):
        desc = "PR for review.\n### **Labels**\nbug"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_generic_type_at_start(self):
        desc = "### **Type**\nfeat"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_generic_type_with_leading_not_detected(self):
        desc = "Summary.\n### **Type**\nfeat"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False


# ---------------------------------------------------------------------------
# Original startswith cases still work
# ---------------------------------------------------------------------------

class TestOriginalStartswithCases:
    def test_standard_pr_type_at_start(self):
        desc = "### **PR Type**\nbug fix\n### **PR Description**\nFixed."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_standard_pr_description_at_start(self):
        desc = "### **PR Description**\nFixed the issue."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True

    def test_standard_generated_marker_at_start(self):
        desc = "### \U0001f916 Generated by PR Agent\nSome output."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------

class TestEdgeCases:
    def test_empty_description(self):
        assert _make_provider("")._is_generated_by_pr_agent("") is False

    def test_only_whitespace(self):
        assert _make_provider("   \n  ")._is_generated_by_pr_agent("   \n  ") is False

    def test_partial_header_not_match(self):
        desc = "### **PR Typ**\nmissing the e"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_case_insensitive_marker(self):
        desc = "<!-- PR-AGENT-GENERATED -->\n### **PR Type**\nfix"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True


class TestQuotedHeadersAreNotOurs:
    """A human description that quotes our headers must not be read as generated,
    otherwise get_user_description() returns '' and their text is lost."""

    def test_blockquoted_header_is_not_generated(self):
        desc = ("For reference the bot emits:\n\n"
                "> ### **PR Type**\n> Bug fix\n\nLeave my text alone.")
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_inline_backticked_header_is_not_generated(self):
        desc = "Our template starts with `### **PR Type**` which I am not using here."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_indented_header_is_not_generated(self):
        desc = "Example:\n\n    ### **PR Type**\n    Bug fix\n\nNot mine."
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is False

    def test_leading_content_before_header_is_still_generated(self):
        desc = "Fixes #42\n### **PR Type**\nBug fix"
        assert _make_provider(desc)._is_generated_by_pr_agent(desc.lower()) is True
